- name: debian | Installing freeIPA Pre-Reqs
  apt:
    name: "{{ freeIPA_server_debian_pre_reqs }}"
    state: present
  become: true

- name: debian | Configuring rng-tools
  template:
    src: etc/default/rng-tools.j2
    dest: /etc/default/rng-tools
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  register: _freeIPA_server_rng_tools_configured

- name: debian | Ensuring rng-tools Service Is Enabled
  service:
    name: rng-tools
    enabled: true
  become: true

- name: debian | Restarting rng-tools Service (When service is reconfigured)
  service:
    name: rng-tools
    state: restarted
  become: true
  when: _freeIPA_server_rng_tools_configured['changed']

- name: debian | Installing freeIPA Server Packages
  apt:
    name: "{{ freeIPA_server_debian_packages }}"
    state: present
  become: true
