dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: mrlesmithjr/bionic64
    memory: 2048
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.250.10
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
